name: Build

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
      - "Makefile"
      - "pom.xml"

jobs:
  cancel-old-build:
    name: Cancel previous builds
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-linux:
    runs-on: ubuntu-latest
    needs: cancel-old-build
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Build
        run: |
          make build
